[2024-01-11T16:25:46.381+0000] {processor.py:153} INFO - Started process (PID=53) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:25:46.383+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:25:46.385+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:25:46.385+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:25:46.793+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:25:47.414+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:25:47.414+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:rds_test_01_11
[2024-01-11T16:25:47.468+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:25:47.468+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:rds_test_01_11
[2024-01-11T16:25:47.522+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:25:47.518+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:rds_test_01_11
[2024-01-11T16:25:47.524+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:25:47.524+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:25:47.595+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:25:47.594+0000] {dag.py:2711} INFO - Creating ORM DAG for rds_test_01_11
[2024-01-11T16:25:47.653+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:25:47.652+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to 2024-01-09T00:00:00+00:00, run_after=2024-01-09T00:00:00+00:00
[2024-01-11T16:25:47.759+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 1.387 seconds
[2024-01-11T16:26:18.478+0000] {processor.py:153} INFO - Started process (PID=131) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:26:18.479+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:26:18.480+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:26:18.480+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:26:18.572+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:26:18.602+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:26:18.602+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:26:18.637+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:26:18.637+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to 2024-01-09T00:00:00+00:00, run_after=2024-01-09T00:00:00+00:00
[2024-01-11T16:26:18.669+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.194 seconds
[2024-01-11T16:26:48.965+0000] {processor.py:153} INFO - Started process (PID=208) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:26:48.967+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:26:48.968+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:26:48.968+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:26:49.119+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:26:49.166+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:26:49.166+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:26:49.226+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:26:49.226+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to 2024-01-09T00:00:00+00:00, run_after=2024-01-09T00:00:00+00:00
[2024-01-11T16:26:49.272+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.312 seconds
[2024-01-11T16:27:20.051+0000] {processor.py:153} INFO - Started process (PID=291) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:27:20.053+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:27:20.054+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:27:20.054+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:27:20.211+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:27:20.273+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:27:20.273+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:27:20.339+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:27:20.339+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to None, run_after=None
[2024-01-11T16:27:20.390+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.346 seconds
[2024-01-11T16:27:50.997+0000] {processor.py:153} INFO - Started process (PID=368) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:27:51.000+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:27:51.002+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:27:51.002+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:27:51.193+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:27:51.247+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:27:51.247+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:27:51.330+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:27:51.329+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to None, run_after=None
[2024-01-11T16:27:51.416+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.429 seconds
[2024-01-11T16:28:22.061+0000] {processor.py:153} INFO - Started process (PID=436) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:28:22.062+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:28:22.063+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:28:22.062+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:28:22.135+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:28:22.166+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:28:22.166+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:28:22.196+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:28:22.196+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to None, run_after=None
[2024-01-11T16:28:22.226+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.169 seconds
[2024-01-11T16:28:52.570+0000] {processor.py:153} INFO - Started process (PID=513) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:28:52.571+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:28:52.573+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:28:52.573+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:28:52.738+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:28:52.784+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:28:52.783+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:28:52.835+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:28:52.834+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to None, run_after=None
[2024-01-11T16:28:52.874+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.311 seconds
[2024-01-11T16:29:23.094+0000] {processor.py:153} INFO - Started process (PID=590) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:29:23.095+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:29:23.097+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:29:23.096+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:29:23.280+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:29:23.341+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:29:23.340+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:29:23.447+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:29:23.447+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to None, run_after=None
[2024-01-11T16:29:23.515+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.428 seconds
[2024-01-11T16:29:53.922+0000] {processor.py:153} INFO - Started process (PID=676) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:29:53.923+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:29:53.926+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:29:53.925+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:29:54.056+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:29:54.090+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:29:54.090+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:29:54.142+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:29:54.142+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to None, run_after=None
[2024-01-11T16:29:54.196+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.278 seconds
[2024-01-11T16:30:24.274+0000] {processor.py:153} INFO - Started process (PID=760) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:30:24.276+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:30:24.278+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:30:24.278+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:30:24.421+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:30:24.478+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:30:24.478+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:30:24.542+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:30:24.542+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to None, run_after=None
[2024-01-11T16:30:24.593+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.326 seconds
[2024-01-11T16:30:54.789+0000] {processor.py:153} INFO - Started process (PID=837) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:30:54.790+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:30:54.792+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:30:54.791+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:30:54.915+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:30:54.955+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:30:54.955+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:30:55.005+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:30:55.004+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to None, run_after=None
[2024-01-11T16:30:55.046+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.264 seconds
[2024-01-11T16:31:25.363+0000] {processor.py:153} INFO - Started process (PID=913) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:31:25.364+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:31:25.364+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:31:25.364+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:31:25.434+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:31:25.460+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:31:25.460+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:31:25.488+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:31:25.488+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to None, run_after=None
[2024-01-11T16:31:25.515+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.156 seconds
[2024-01-11T16:31:56.030+0000] {processor.py:153} INFO - Started process (PID=990) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:31:56.031+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:31:56.032+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:31:56.032+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:31:56.184+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:31:56.239+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:31:56.239+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:31:56.307+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:31:56.307+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to None, run_after=None
[2024-01-11T16:31:56.362+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.337 seconds
[2024-01-11T16:32:27.372+0000] {processor.py:153} INFO - Started process (PID=1067) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:32:27.372+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:32:27.373+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:32:27.373+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:32:27.447+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:32:27.476+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:32:27.476+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:32:27.506+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:32:27.506+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to None, run_after=None
[2024-01-11T16:32:27.551+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.185 seconds
[2024-01-11T16:32:57.958+0000] {processor.py:153} INFO - Started process (PID=1144) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:32:57.959+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:32:57.960+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:32:57.960+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:32:58.030+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:32:58.060+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:32:58.060+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:32:58.091+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:32:58.090+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to None, run_after=None
[2024-01-11T16:32:58.122+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.166 seconds
[2024-01-11T16:33:28.168+0000] {processor.py:153} INFO - Started process (PID=1221) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:33:28.169+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:33:28.170+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:33:28.170+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:33:28.256+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:33:28.288+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:33:28.288+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:33:28.322+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:33:28.322+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to None, run_after=None
[2024-01-11T16:33:28.358+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.193 seconds
[2024-01-11T16:33:58.567+0000] {processor.py:153} INFO - Started process (PID=1298) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:33:58.569+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:33:58.572+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:33:58.572+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:33:58.865+0000] {processor.py:753} INFO - DAG(s) dict_keys(['rds_test_01_11']) retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:33:58.949+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:33:58.949+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-11T16:33:59.101+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:33:59.101+0000] {dag.py:3441} INFO - Setting next_dagrun for rds_test_01_11 to None, run_after=None
[2024-01-11T16:33:59.221+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.664 seconds
[2024-01-11T16:35:37.209+0000] {processor.py:153} INFO - Started process (PID=53) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:35:37.211+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:35:37.213+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:35:37.213+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:35:37.326+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:35:37.315+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:35:37.330+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:35:37.387+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.188 seconds
[2024-01-11T16:36:08.388+0000] {processor.py:153} INFO - Started process (PID=130) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:36:08.389+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:36:08.390+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:36:08.390+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:36:08.416+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:36:08.413+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:36:08.417+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:36:08.437+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.052 seconds
[2024-01-11T16:36:38.543+0000] {processor.py:153} INFO - Started process (PID=199) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:36:38.545+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:36:38.548+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:36:38.547+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:36:38.620+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:36:38.608+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:36:38.624+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:36:38.680+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.147 seconds
[2024-01-11T16:38:28.613+0000] {processor.py:153} INFO - Started process (PID=54) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:38:28.616+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:38:28.618+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:38:28.618+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:38:28.701+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:38:28.693+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:38:28.705+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:38:28.746+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.140 seconds
[2024-01-11T16:38:58.993+0000] {processor.py:153} INFO - Started process (PID=131) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:38:58.995+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:38:58.999+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:38:58.999+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:38:59.058+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:38:59.049+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:38:59.062+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:38:59.126+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.141 seconds
[2024-01-11T16:39:29.217+0000] {processor.py:153} INFO - Started process (PID=208) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:39:29.218+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:39:29.220+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:39:29.220+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:39:29.268+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:39:29.260+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:39:29.271+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:39:29.309+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.099 seconds
[2024-01-11T16:39:59.785+0000] {processor.py:153} INFO - Started process (PID=278) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:39:59.787+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:39:59.790+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:39:59.789+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:39:59.892+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:39:59.877+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:39:59.918+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:40:00.070+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.312 seconds
[2024-01-11T16:42:37.873+0000] {processor.py:153} INFO - Started process (PID=63) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:42:37.892+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:42:37.895+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:42:37.894+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:42:38.448+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:42:38.294+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:42:38.474+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:42:38.679+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.826 seconds
[2024-01-11T16:43:08.971+0000] {processor.py:153} INFO - Started process (PID=132) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:43:08.972+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:43:08.973+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:43:08.972+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:43:09.005+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:43:08.999+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:43:09.007+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:43:09.034+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.067 seconds
[2024-01-11T16:43:39.461+0000] {processor.py:153} INFO - Started process (PID=210) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:43:39.469+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:43:39.472+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:43:39.471+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:43:39.520+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:43:39.512+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:43:39.523+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:43:39.554+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.098 seconds
[2024-01-11T16:44:10.507+0000] {processor.py:153} INFO - Started process (PID=288) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:44:10.507+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:44:10.508+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:44:10.508+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:44:10.531+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:44:10.527+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:44:10.532+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:44:10.554+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.051 seconds
[2024-01-11T16:44:41.188+0000] {processor.py:153} INFO - Started process (PID=366) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:44:41.189+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:44:41.190+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:44:41.190+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:44:41.224+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:44:41.218+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:44:41.226+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:44:41.259+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.075 seconds
[2024-01-11T16:45:11.734+0000] {processor.py:153} INFO - Started process (PID=444) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:45:11.736+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:45:11.739+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:45:11.738+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:45:11.836+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:45:11.825+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:45:11.844+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:45:11.973+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.246 seconds
[2024-01-11T16:45:42.259+0000] {processor.py:153} INFO - Started process (PID=506) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:45:42.260+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:45:42.261+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:45:42.260+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:45:42.284+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:45:42.280+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:45:42.285+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:45:42.306+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.049 seconds
[2024-01-11T16:46:13.061+0000] {processor.py:153} INFO - Started process (PID=593) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:46:13.062+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:46:13.063+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:46:13.062+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:46:13.095+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:46:13.090+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:46:13.097+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:46:13.128+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.071 seconds
[2024-01-11T16:46:43.313+0000] {processor.py:153} INFO - Started process (PID=671) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:46:43.315+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:46:43.317+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:46:43.317+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:46:43.408+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:46:43.392+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:46:43.411+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:46:43.468+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.165 seconds
[2024-01-11T16:47:14.370+0000] {processor.py:153} INFO - Started process (PID=740) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:47:14.372+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:47:14.385+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:47:14.382+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:47:14.496+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:47:14.486+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:47:14.501+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:47:14.585+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.231 seconds
[2024-01-11T16:47:45.112+0000] {processor.py:153} INFO - Started process (PID=818) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:47:45.113+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:47:45.113+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:47:45.113+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:47:45.134+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:47:45.131+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:47:45.136+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:47:45.157+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.048 seconds
[2024-01-11T16:48:15.463+0000] {processor.py:153} INFO - Started process (PID=912) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:48:15.464+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:48:15.466+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:48:15.465+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:48:15.493+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:48:15.489+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:48:15.495+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:48:15.530+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.070 seconds
[2024-01-11T16:48:45.673+0000] {processor.py:153} INFO - Started process (PID=974) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:48:45.674+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:48:45.675+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:48:45.675+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:48:45.697+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:48:45.694+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:48:45.699+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:48:45.722+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.052 seconds
[2024-01-11T16:49:16.366+0000] {processor.py:153} INFO - Started process (PID=1069) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:49:16.367+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:49:16.368+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:49:16.368+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:49:16.395+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:49:16.390+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:49:16.397+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:49:16.424+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.062 seconds
[2024-01-11T16:49:46.758+0000] {processor.py:153} INFO - Started process (PID=1147) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:49:46.760+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:49:46.761+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:49:46.761+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:49:46.794+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:49:46.788+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:49:46.796+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:49:46.835+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.081 seconds
[2024-01-11T16:50:17.152+0000] {processor.py:153} INFO - Started process (PID=1225) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:50:17.153+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:50:17.155+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:50:17.154+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:50:17.200+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:50:17.193+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:50:17.203+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:50:17.243+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.102 seconds
[2024-01-11T16:50:47.432+0000] {processor.py:153} INFO - Started process (PID=1303) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:50:47.434+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:50:47.435+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:50:47.435+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:50:47.491+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:50:47.482+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:50:47.495+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:50:47.555+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.130 seconds
[2024-01-11T16:51:17.849+0000] {processor.py:153} INFO - Started process (PID=1381) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:51:17.850+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:51:17.851+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:51:17.851+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:51:17.873+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:51:17.870+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:51:17.874+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:51:17.895+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.049 seconds
[2024-01-11T16:52:31.527+0000] {processor.py:153} INFO - Started process (PID=54) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:52:31.529+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:52:31.531+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:52:31.530+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:52:31.596+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:52:31.585+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:52:31.599+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:52:31.668+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.148 seconds
[2024-01-11T16:53:02.083+0000] {processor.py:153} INFO - Started process (PID=132) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T16:53:02.084+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T16:53:02.085+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:53:02.085+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T16:53:02.110+0000] {logging_mixin.py:137} INFO - [2024-01-11T16:53:02.106+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 5, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
[2024-01-11T16:53:02.112+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T16:53:02.135+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.054 seconds
[2024-01-11T17:04:25.270+0000] {processor.py:153} INFO - Started process (PID=86) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:04:25.281+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:04:25.285+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:04:25.285+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:04:26.761+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:04:26.730+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:04:26.769+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:04:26.900+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 1.654 seconds
[2024-01-11T17:04:57.188+0000] {processor.py:153} INFO - Started process (PID=147) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:04:57.196+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:04:57.208+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:04:57.207+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:04:57.800+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:04:57.780+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:04:57.814+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:04:57.964+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.787 seconds
[2024-01-11T17:05:28.632+0000] {processor.py:153} INFO - Started process (PID=227) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:05:28.636+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:05:28.639+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:05:28.638+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:05:28.955+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:05:28.942+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:05:28.959+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:05:29.015+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.401 seconds
[2024-01-11T17:05:59.321+0000] {processor.py:153} INFO - Started process (PID=299) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:05:59.323+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:05:59.327+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:05:59.326+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:05:59.578+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:05:59.555+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:05:59.587+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:05:59.698+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.388 seconds
[2024-01-11T17:06:30.081+0000] {processor.py:153} INFO - Started process (PID=367) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:06:30.082+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:06:30.084+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:06:30.084+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:06:30.366+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:06:30.356+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:06:30.370+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:06:30.445+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.373 seconds
[2024-01-11T17:07:03.109+0000] {processor.py:153} INFO - Started process (PID=440) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:07:03.124+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:07:03.130+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:07:03.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:07:04.410+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:07:04.117+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:07:04.434+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:07:05.177+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 2.076 seconds
[2024-01-11T17:07:35.774+0000] {processor.py:153} INFO - Started process (PID=510) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:07:35.783+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:07:35.788+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:07:35.788+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:07:36.487+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:07:36.415+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:07:36.492+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:07:36.634+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.884 seconds
[2024-01-11T17:08:07.623+0000] {processor.py:153} INFO - Started process (PID=580) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:08:07.628+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:08:07.642+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:08:07.641+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:08:08.308+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:08:08.272+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:08:08.332+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:08:08.442+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.838 seconds
[2024-01-11T17:08:38.909+0000] {processor.py:153} INFO - Started process (PID=652) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:08:38.914+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:08:38.927+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:08:38.920+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:08:39.590+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:08:39.497+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:08:39.647+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:08:39.868+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.992 seconds
[2024-01-11T17:09:10.050+0000] {processor.py:153} INFO - Started process (PID=721) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:09:10.051+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:09:10.052+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:09:10.052+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:09:10.217+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:09:10.211+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:09:10.220+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:09:10.257+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.213 seconds
[2024-01-11T17:09:40.959+0000] {processor.py:153} INFO - Started process (PID=798) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:09:40.963+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:09:40.966+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:09:40.966+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:09:41.487+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:09:41.454+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:09:41.494+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:09:41.633+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.688 seconds
[2024-01-11T17:10:12.307+0000] {processor.py:153} INFO - Started process (PID=860) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:10:12.317+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:10:12.321+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:10:12.320+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:10:12.770+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:10:12.759+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:10:12.774+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:10:12.856+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.569 seconds
[2024-01-11T17:10:44.052+0000] {processor.py:153} INFO - Started process (PID=931) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:10:44.091+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:10:44.105+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:10:44.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:10:45.048+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:10:44.951+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:10:45.061+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:10:45.264+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 1.230 seconds
[2024-01-11T17:13:13.804+0000] {processor.py:153} INFO - Started process (PID=70) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:13:13.810+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:13:13.813+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:13:13.812+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:13:14.444+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:13:14.426+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:13:14.452+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:13:14.543+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.749 seconds
[2024-01-11T17:13:44.855+0000] {processor.py:153} INFO - Started process (PID=151) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:13:44.862+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:13:44.865+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:13:44.865+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:13:45.439+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:13:45.390+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:13:45.449+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:13:45.666+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.830 seconds
[2024-01-11T17:14:16.708+0000] {processor.py:153} INFO - Started process (PID=222) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:14:16.712+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:14:16.715+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:14:16.715+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:14:17.306+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:14:17.275+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:14:17.329+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:14:17.487+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.798 seconds
[2024-01-11T17:14:49.605+0000] {processor.py:153} INFO - Started process (PID=287) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:14:49.622+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:14:49.638+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:14:49.637+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:14:50.860+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:14:50.746+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:14:50.865+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:14:51.077+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 1.435 seconds
[2024-01-11T17:15:21.442+0000] {processor.py:153} INFO - Started process (PID=356) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:15:21.449+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:15:21.457+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:15:21.456+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:15:22.031+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:15:21.991+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:15:22.051+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:15:22.204+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.786 seconds
[2024-01-11T17:15:52.506+0000] {processor.py:153} INFO - Started process (PID=426) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:15:52.512+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:15:52.515+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:15:52.515+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:15:53.304+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:15:53.271+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:15:53.314+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:15:53.401+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.908 seconds
[2024-01-11T17:16:29.937+0000] {processor.py:153} INFO - Started process (PID=505) to work on /opt/airflow/dags/rds_test.py
[2024-01-11T17:16:29.939+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/rds_test.py for tasks to queue
[2024-01-11T17:16:29.942+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:16:29.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/rds_test.py
[2024-01-11T17:16:30.244+0000] {logging_mixin.py:137} INFO - [2024-01-11T17:16:30.233+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/rds_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rds_test.py", line 85, in <module>
    message=f'```\n{table}\n```',
NameError: name 'table' is not defined
[2024-01-11T17:16:30.257+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/rds_test.py
[2024-01-11T17:16:30.336+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/rds_test.py took 0.412 seconds
