[2024-01-13T12:58:41.803+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jobinfo_jobplanet.create_infomation_s3 manual__2024-01-13T12:58:34.079612+00:00 [queued]>
[2024-01-13T12:58:41.812+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jobinfo_jobplanet.create_infomation_s3 manual__2024-01-13T12:58:34.079612+00:00 [queued]>
[2024-01-13T12:58:41.812+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-13T12:58:41.812+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-13T12:58:41.812+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-13T12:58:41.828+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_infomation_s3> on 2024-01-13 12:58:34.079612+00:00
[2024-01-13T12:58:41.836+0000] {standard_task_runner.py:55} INFO - Started process 450 to run task
[2024-01-13T12:58:41.840+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'jobinfo_jobplanet', 'create_infomation_s3', 'manual__2024-01-13T12:58:34.079612+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/jobinfo_jobplanet.py', '--cfg-path', '/tmp/tmpwv_xbqpg']
[2024-01-13T12:58:41.840+0000] {standard_task_runner.py:83} INFO - Job 365: Subtask create_infomation_s3
[2024-01-13T12:58:42.180+0000] {task_command.py:388} INFO - Running <TaskInstance: jobinfo_jobplanet.create_infomation_s3 manual__2024-01-13T12:58:34.079612+00:00 [running]> on host 7b77d04f99d6
[2024-01-13T12:58:42.293+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=jobinfo_jobplanet
AIRFLOW_CTX_TASK_ID=create_infomation_s3
AIRFLOW_CTX_EXECUTION_DATE=2024-01-13T12:58:34.079612+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-13T12:58:34.079612+00:00
[2024-01-13T12:58:43.073+0000] {jobinfo_jobplanet.py:57} INFO - 11111111111111111
[2024-01-13T12:58:43.073+0000] {jobinfo_jobplanet.py:58} INFO - <selenium.webdriver.remote.webdriver.WebDriver (session="19760dca01b782fd4bea3342a6164fd0")>
[2024-01-13T12:58:43.106+0000] {jobinfo_jobplanet.py:64} INFO - 2222222222222222222222222
[2024-01-13T12:58:43.106+0000] {jobinfo_jobplanet.py:65} INFO - <selenium.webdriver.remote.webdriver.WebDriver (session="19760dca01b782fd4bea3342a6164fd0")>
[2024-01-13T12:58:44.230+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/jobinfo_jobplanet.py", line 88, in create_infomation_s3
    driver = jobplanet_login()
  File "/opt/airflow/dags/jobinfo_jobplanet.py", line 70, in jobplanet_login
    id_input = driver.find_element(By.ID, "user_email")
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 739, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="user_email"]"}
  (Session info: chrome-headless-shell=120.0.6099.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x56161f861f83 <unknown>
#1 0x56161f51acf7 <unknown>
#2 0x56161f56a99e <unknown>
#3 0x56161f56aaa1 <unknown>
#4 0x56161f5b5d64 <unknown>
#5 0x56161f5940dd <unknown>
#6 0x56161f5b3006 <unknown>
#7 0x56161f593e53 <unknown>
#8 0x56161f55bdd4 <unknown>
#9 0x56161f55d1de <unknown>
#10 0x56161f826531 <unknown>
#11 0x56161f82a455 <unknown>
#12 0x56161f812f55 <unknown>
#13 0x56161f82b0ef <unknown>
#14 0x56161f7f699f <unknown>
#15 0x56161f84f008 <unknown>
#16 0x56161f84f1d7 <unknown>
#17 0x56161f861124 <unknown>
#18 0x7ffa33f42ac3 <unknown>

[2024-01-13T12:58:44.248+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=jobinfo_jobplanet, task_id=create_infomation_s3, execution_date=20240113T125834, start_date=20240113T125841, end_date=20240113T125844
[2024-01-13T12:58:44.291+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 365 for task create_infomation_s3 (Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="user_email"]"}
  (Session info: chrome-headless-shell=120.0.6099.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x56161f861f83 <unknown>
#1 0x56161f51acf7 <unknown>
#2 0x56161f56a99e <unknown>
#3 0x56161f56aaa1 <unknown>
#4 0x56161f5b5d64 <unknown>
#5 0x56161f5940dd <unknown>
#6 0x56161f5b3006 <unknown>
#7 0x56161f593e53 <unknown>
#8 0x56161f55bdd4 <unknown>
#9 0x56161f55d1de <unknown>
#10 0x56161f826531 <unknown>
#11 0x56161f82a455 <unknown>
#12 0x56161f812f55 <unknown>
#13 0x56161f82b0ef <unknown>
#14 0x56161f7f699f <unknown>
#15 0x56161f84f008 <unknown>
#16 0x56161f84f1d7 <unknown>
#17 0x56161f861124 <unknown>
#18 0x7ffa33f42ac3 <unknown>
; 450)
[2024-01-13T12:58:44.316+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-13T12:58:44.502+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
