[2024-01-11T17:44:53.781+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: rds_test_2.send_slack manual__2024-01-11T17:44:41.162304+00:00 [queued]>
[2024-01-11T17:44:53.813+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: rds_test_2.send_slack manual__2024-01-11T17:44:41.162304+00:00 [queued]>
[2024-01-11T17:44:53.814+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-11T17:44:53.815+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-01-11T17:44:53.816+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-11T17:44:53.861+0000] {taskinstance.py:1300} INFO - Executing <Task(SlackWebhookOperator): send_slack> on 2024-01-11 17:44:41.162304+00:00
[2024-01-11T17:44:53.869+0000] {standard_task_runner.py:55} INFO - Started process 194 to run task
[2024-01-11T17:44:53.876+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'rds_test_2', 'send_slack', 'manual__2024-01-11T17:44:41.162304+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/rds_test_2.py', '--cfg-path', '/tmp/tmpv2rgn01s']
[2024-01-11T17:44:53.877+0000] {standard_task_runner.py:83} INFO - Job 99: Subtask send_slack
[2024-01-11T17:44:53.997+0000] {task_command.py:388} INFO - Running <TaskInstance: rds_test_2.send_slack manual__2024-01-11T17:44:41.162304+00:00 [running]> on host 3d6f932ce29c
[2024-01-11T17:44:54.118+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=rds_test_2
AIRFLOW_CTX_TASK_ID=send_slack
AIRFLOW_CTX_EXECUTION_DATE=2024-01-11T17:44:41.162304+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-11T17:44:41.162304+00:00
[2024-01-11T17:44:54.120+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/slack/operators/slack_webhook.py:173: UserWarning: Found unexpected keyword-argument(s) 'link_names' in `send` method. This argument(s) have no effect.
  link_names=self.link_names,

[2024-01-11T17:44:54.134+0000] {base.py:73} INFO - Using connection ID 'slack_conn' for task execution.
[2024-01-11T17:44:54.137+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/slack/hooks/slack_webhook.py:226: DeprecationWarning: Found Slack Webhook Token URL in Connection 'slack_conn' `host` and `password` field is empty. This behaviour deprecated and could expose you token in the UI and will be removed in a future releases.
  return WebhookClient(**self._get_conn_params())

[2024-01-11T17:44:54.588+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=rds_test_2, task_id=send_slack, execution_date=20240111T174441, start_date=20240111T174453, end_date=20240111T174454
[2024-01-11T17:44:54.650+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-01-11T17:44:54.680+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
