[2024-01-11T17:50:20.661+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: rds_test_2.send_slack manual__2024-01-11T17:50:09.737259+00:00 [queued]>
[2024-01-11T17:50:20.678+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: rds_test_2.send_slack manual__2024-01-11T17:50:09.737259+00:00 [queued]>
[2024-01-11T17:50:20.679+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-11T17:50:20.680+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-01-11T17:50:20.681+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-11T17:50:20.706+0000] {taskinstance.py:1300} INFO - Executing <Task(SlackWebhookOperator): send_slack> on 2024-01-11 17:50:09.737259+00:00
[2024-01-11T17:50:20.712+0000] {standard_task_runner.py:55} INFO - Started process 140 to run task
[2024-01-11T17:50:20.717+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'rds_test_2', 'send_slack', 'manual__2024-01-11T17:50:09.737259+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/rds_test_2.py', '--cfg-path', '/tmp/tmp7le9lxg0']
[2024-01-11T17:50:20.718+0000] {standard_task_runner.py:83} INFO - Job 104: Subtask send_slack
[2024-01-11T17:50:20.824+0000] {task_command.py:388} INFO - Running <TaskInstance: rds_test_2.send_slack manual__2024-01-11T17:50:09.737259+00:00 [running]> on host 3d6f932ce29c
[2024-01-11T17:50:20.941+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=rds_test_2
AIRFLOW_CTX_TASK_ID=send_slack
AIRFLOW_CTX_EXECUTION_DATE=2024-01-11T17:50:09.737259+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-11T17:50:09.737259+00:00
[2024-01-11T17:50:20.943+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/slack/operators/slack_webhook.py:173: UserWarning: Found unexpected keyword-argument(s) 'link_names' in `send` method. This argument(s) have no effect.
  link_names=self.link_names,

[2024-01-11T17:50:20.957+0000] {base.py:73} INFO - Using connection ID 'slack_conn' for task execution.
[2024-01-11T17:50:20.960+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/slack/hooks/slack_webhook.py:226: DeprecationWarning: Found Slack Webhook Token URL in Connection 'slack_conn' `host` and `password` field is empty. This behaviour deprecated and could expose you token in the UI and will be removed in a future releases.
  return WebhookClient(**self._get_conn_params())

[2024-01-11T17:50:21.561+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=rds_test_2, task_id=send_slack, execution_date=20240111T175009, start_date=20240111T175020, end_date=20240111T175021
[2024-01-11T17:50:21.612+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-01-11T17:50:21.632+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
