[2024-01-13T12:55:19.141+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jobinfo_jobplanet.create_infomation_s3 manual__2024-01-13T12:55:11.264159+00:00 [queued]>
[2024-01-13T12:55:19.164+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jobinfo_jobplanet.create_infomation_s3 manual__2024-01-13T12:55:11.264159+00:00 [queued]>
[2024-01-13T12:55:19.165+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-13T12:55:19.167+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-13T12:55:19.167+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-13T12:55:19.216+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_infomation_s3> on 2024-01-13 12:55:11.264159+00:00
[2024-01-13T12:55:19.237+0000] {standard_task_runner.py:55} INFO - Started process 282 to run task
[2024-01-13T12:55:19.244+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'jobinfo_jobplanet', 'create_infomation_s3', 'manual__2024-01-13T12:55:11.264159+00:00', '--job-id', '362', '--raw', '--subdir', 'DAGS_FOLDER/jobinfo_jobplanet.py', '--cfg-path', '/tmp/tmp10z60ehq']
[2024-01-13T12:55:19.245+0000] {standard_task_runner.py:83} INFO - Job 362: Subtask create_infomation_s3
[2024-01-13T12:55:19.663+0000] {task_command.py:388} INFO - Running <TaskInstance: jobinfo_jobplanet.create_infomation_s3 manual__2024-01-13T12:55:11.264159+00:00 [running]> on host 7b77d04f99d6
[2024-01-13T12:55:19.815+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=jobinfo_jobplanet
AIRFLOW_CTX_TASK_ID=create_infomation_s3
AIRFLOW_CTX_EXECUTION_DATE=2024-01-13T12:55:11.264159+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-13T12:55:11.264159+00:00
[2024-01-13T12:55:21.548+0000] {jobinfo_jobplanet.py:57} INFO - 11111111111111111
[2024-01-13T12:55:21.548+0000] {jobinfo_jobplanet.py:58} INFO - driver
[2024-01-13T12:55:21.614+0000] {jobinfo_jobplanet.py:64} INFO - 2222222222222222222222222
[2024-01-13T12:55:21.614+0000] {jobinfo_jobplanet.py:65} INFO - <selenium.webdriver.remote.webdriver.WebDriver (session="4a9219febe1611d1703994f96e214ea2")>
[2024-01-13T12:55:22.804+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/jobinfo_jobplanet.py", line 88, in create_infomation_s3
    driver = jobplanet_login()
  File "/opt/airflow/dags/jobinfo_jobplanet.py", line 70, in jobplanet_login
    id_input = driver.find_element(By.ID, "user_email")
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 739, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="user_email"]"}
  (Session info: chrome-headless-shell=120.0.6099.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55a0694a3f83 <unknown>
#1 0x55a06915ccf7 <unknown>
#2 0x55a0691ac99e <unknown>
#3 0x55a0691acaa1 <unknown>
#4 0x55a0691f7d64 <unknown>
#5 0x55a0691d60dd <unknown>
#6 0x55a0691f5006 <unknown>
#7 0x55a0691d5e53 <unknown>
#8 0x55a06919ddd4 <unknown>
#9 0x55a06919f1de <unknown>
#10 0x55a069468531 <unknown>
#11 0x55a06946c455 <unknown>
#12 0x55a069454f55 <unknown>
#13 0x55a06946d0ef <unknown>
#14 0x55a06943899f <unknown>
#15 0x55a069491008 <unknown>
#16 0x55a0694911d7 <unknown>
#17 0x55a0694a3124 <unknown>
#18 0x7f69d9a9dac3 <unknown>

[2024-01-13T12:55:22.813+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=jobinfo_jobplanet, task_id=create_infomation_s3, execution_date=20240113T125511, start_date=20240113T125519, end_date=20240113T125522
[2024-01-13T12:55:22.827+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 362 for task create_infomation_s3 (Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="user_email"]"}
  (Session info: chrome-headless-shell=120.0.6099.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55a0694a3f83 <unknown>
#1 0x55a06915ccf7 <unknown>
#2 0x55a0691ac99e <unknown>
#3 0x55a0691acaa1 <unknown>
#4 0x55a0691f7d64 <unknown>
#5 0x55a0691d60dd <unknown>
#6 0x55a0691f5006 <unknown>
#7 0x55a0691d5e53 <unknown>
#8 0x55a06919ddd4 <unknown>
#9 0x55a06919f1de <unknown>
#10 0x55a069468531 <unknown>
#11 0x55a06946c455 <unknown>
#12 0x55a069454f55 <unknown>
#13 0x55a06946d0ef <unknown>
#14 0x55a06943899f <unknown>
#15 0x55a069491008 <unknown>
#16 0x55a0694911d7 <unknown>
#17 0x55a0694a3124 <unknown>
#18 0x7f69d9a9dac3 <unknown>
; 282)
[2024-01-13T12:55:22.869+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-13T12:55:23.100+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
