[2024-01-11T18:08:55.175+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: rds_test_2.send_slack manual__2024-01-11T18:03:40.785046+00:00 [queued]>
[2024-01-11T18:08:55.197+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: rds_test_2.send_slack manual__2024-01-11T18:03:40.785046+00:00 [queued]>
[2024-01-11T18:08:55.198+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-11T18:08:55.199+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-01-11T18:08:55.200+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-11T18:08:55.239+0000] {taskinstance.py:1300} INFO - Executing <Task(SlackWebhookOperator): send_slack> on 2024-01-11 18:03:40.785046+00:00
[2024-01-11T18:08:55.247+0000] {standard_task_runner.py:55} INFO - Started process 72 to run task
[2024-01-11T18:08:55.253+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'rds_test_2', 'send_slack', 'manual__2024-01-11T18:03:40.785046+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/rds_test_2.py', '--cfg-path', '/tmp/tmpwck4r63b']
[2024-01-11T18:08:55.255+0000] {standard_task_runner.py:83} INFO - Job 118: Subtask send_slack
[2024-01-11T18:08:55.391+0000] {task_command.py:388} INFO - Running <TaskInstance: rds_test_2.send_slack manual__2024-01-11T18:03:40.785046+00:00 [running]> on host 3d6f932ce29c
[2024-01-11T18:08:55.619+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=rds_test_2
AIRFLOW_CTX_TASK_ID=send_slack
AIRFLOW_CTX_EXECUTION_DATE=2024-01-11T18:03:40.785046+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-11T18:03:40.785046+00:00
[2024-01-11T18:08:55.622+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/slack/operators/slack_webhook.py:173: UserWarning: Found unexpected keyword-argument(s) 'link_names' in `send` method. This argument(s) have no effect.
  link_names=self.link_names,

[2024-01-11T18:08:55.643+0000] {base.py:73} INFO - Using connection ID 'slack_conn' for task execution.
[2024-01-11T18:08:55.648+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/slack/hooks/slack_webhook.py:226: DeprecationWarning: Found Slack Webhook Token URL in Connection 'slack_conn' `host` and `password` field is empty. This behaviour deprecated and could expose you token in the UI and will be removed in a future releases.
  return WebhookClient(**self._get_conn_params())

[2024-01-11T18:08:56.272+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=rds_test_2, task_id=send_slack, execution_date=20240111T180340, start_date=20240111T180855, end_date=20240111T180856
[2024-01-11T18:08:56.391+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-01-11T18:08:56.456+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
